<<<<<<< HEAD
[dependencies]
restaurant = { path = "../restaurant" }
=======
[package]
name = "restaurant"
version = "0.1.0"
edition = "2024"

description = "A library for managing a restaurant"
authors = ["Dheymison <Dheymison201n.ti@gmail.com>"]
>>>>>>> 6195acf0c98353f07f162cd7d21bf4e8b9a09e18
